eval_on_test: True
num_epochs: 5000
batch_size: 1024
log_iterations: 100
patience: 80
min_train_acc: 99.6
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_train_seqvec/embeddings/bert_embeddings/reduced_embeddings_file.h5'
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_train_seqvec/embeddings/remapped_sequences_file.fasta'
val_embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_val_seqvec/embeddings/bert_embeddings/reduced_embeddings_file.h5'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_val_seqvec/embeddings/remapped_sequences_file.fasta'
test_embeddings: '/mnt/project/bio_embeddings/runs/hannes/embed_test_seqvec/embeddings/bert_embeddings/reduced_embeddings_file.h5'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_test_seqvec/embeddings/remapped_sequences_file.fasta'

# Model parameters
model_type: 'FFN'
model_parameters:
  output_dim: 10
  hidden_dim: 32
  n_hidden_layers: 0
  dropout: 0.25
