experiment_name: ''

num_epochs: 5000
batch_size: 80
log_iterations: 100
patience: 30
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/train.h5'
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/train.fasta'
val_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/val_homreduced.h5'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/val_homreduced.fasta'
test_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/test_as_per_deeploc.h5'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/test_as_per_deeploc.fasta'
key_format: mheinzinger

# Model parameters
model_type: 'AdaptivePooling'
model_parameters:
  dropout: 0.25
  kernel_size: 9
  output_dim: 10
