eval_on_test: True
num_epochs: 5000
batch_size: 150
log_iterations: 100
patience: 40
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings/train_t5-encoderOnly.h5'
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/fasta_files/train.fasta'
val_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings/val_t5-encoderOnly.h5'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/fasta_files/val_homreduced.fasta'
test_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings/test_t5-encoderOnly.h5'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/fasta_files/test_as_per_deeploc.fasta'
remapping_in_hash_format: False
embedding_format: onehot

# Model parameters
model_type: 'LightAttention'
model_parameters:
  dropout: 0.25
  kernel_size: 9
  output_dim: 10
