eval_on_test: True
num_epochs: 5000
batch_size: 32
log_iterations: 100
patience: 30
optimizer_parameters:
  lr: 5.0e-4

# Paths to Data
train_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/train.h5'
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/train.fasta'
val_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/val_homreduced.h5'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/val_homreduced.fasta'
test_embeddings: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/test_as_per_deeploc.h5'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/protein-localization/data/embeddings_t5_Uniref50/test_as_per_deeploc.fasta'
key_format: mheinzinger

# Model parameters
model_type: 'LSTMConv'
model_parameters:
  output_dim: 10
  kernel_size: 9
  lstm_hidden_dim: 256
  n_layers: 2
  dropout: 0.2

