eval_on_test: True
num_epochs: 5000
batch_size: 150
log_iterations: 100
patience: 40
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_train/embeddings/remapped_sequences_file.fasta'
val_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_val/embeddings/remapped_sequences_file.fasta'
test_remapping: '/mnt/project/bio_embeddings/runs/hannes/embed_test/embeddings/remapped_sequences_file.fasta'
train_embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
val_embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
test_embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
embedding_mode: profiles

# Model parameters
model_type: 'LightAttention'
model_parameters:
  dropout: 0.25
  kernel_size: 9
  output_dim: 10
