experiment_name: 'localization_prediction_unirep'

seed: 123
add_start_token: True
num_epochs: 5000
batch_size: 150
log_iterations: 100
patience: 80
optimizer_parameters:
  lr: 5.0e-5

# Paths to Data
train_embeddings: 'data/unirep_embeddings/train/embeddings/embeddings_file.h5'
val_embeddings: 'data/unirep_embeddings/val/embeddings/embeddings_file.h5'
test_embeddings: 'data/unirep_embeddings/deeploc_test/embeddings/embeddings_file.h5'

train_remapping: 'data/unirep_embeddings/train/remapped_sequences_file.fasta'
val_remapping: 'data/unirep_embeddings/val/remapped_sequences_file.fasta'
test_remapping: 'data/unirep_embeddings/deeploc_test/remapped_sequences_file.fasta'
key_format: hash

# Model parameters
model_type: 'LightAttention'
model_parameters:
  dropout: 0.25
  kernel_size: 9
  output_dim: 10
