output_files_name: 'deeploc_test'

log_iterations: 100
n_draws: 1000
batch_size: 2
checkpoints_list:
  - runs/..Uniref50/LightAttention__309_11-04_18-55-27



## T5 deeploc
#embeddings: 'data/embeddings/test_t5-encoderOnly.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False

## pssm deeploc
#embeddings: 'data/embeddings/subCell_all_pssmFile.h5'
#remapping: data/fasta_files/test_as_per_deeploc.fasta
#remapping_in_hash_format: False


# deeploc UNIREF50
embeddings: 'data/embeddings_uniref50/test_as_per_deeploc.h5'
remapping: 'data/embeddings_uniref50/test_as_per_deeploc.fasta'
key_format: mheinzinger

## deeploc UNIREF50 POOLeD
#embeddings: 'data/uniref_embeddings_pooled/test_as_per_deeploc.h5'
#remapping: 'data/uniref_embeddings_pooled/test_as_per_deeploc.fasta'
#key_format: mheinzinger

